name: Newman Run

on:
  pull_request:
    branches:
    - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Newman Action
        uses: matt-ball/newman-action@v0.2.4
        with:
          collection: employee collection.postman_collection.json
          environment: Localhost.postman_environment.json
          

