name: Newman Run

on:
  pull_request:
    branches:
    - master

jobs: 
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: "employee collection.postman_collection.json"
          environment: Localhost.postman_environment.json
